<?php

$user = Factory::create(new User);

// G1

$user->create("aallali",    "aallali",    "amine.allali@hetic.net",       "Amine",        "Allali",                             User::STUDENT, 1);
$user->create("calvarez",   "calvarez",   "camille.alvarez@hetic.net",    "Camille",      "Alvarez de jesus",                   User::STUDENT, 1);
$user->create("yatlan",     "yatlan",     "yoan.atlan@hetic.net",         "Yoan",         "Atlan",                              User::STUDENT, 1);
$user->create("jbelamy",    "jbelamy",    "jules.belamy@hetic.net",       "Jules",        "Belamy",                             User::STUDENT, 1);
$user->create("ncastells",  "ncastells",  "nicolas.castells@hetic.net",   "Nicolas",      "Castells",                           User::STUDENT, 1);
$user->create("achappuy",   "achappuy",   "aymeric.chappuy@hetic.net",    "Aymeric",      "Chappuy",                            User::STUDENT, 1);
$user->create("achassin",   "achassin",   "arthur.chassin@hetic.net",     "Arthur",       "Chassin",                            User::STUDENT, 1);
$user->create("acossid",    "acossid",    "alexandra.cossid@hetic.net",   "Alexandra",    "Cossid",                             User::STUDENT, 1);
$user->create("scumur",     "scumur",     "selim.cumur@hetic.net",        "Sélim",        "Cumur",                              User::STUDENT, 1);
$user->create("adallot",    "adallot",    "alexandre.dallot@hetic.net",   "Alexandre",    "Dallot",                             User::STUDENT, 1);
$user->create("pdegourcy",  "pdegourcy",  "pierre.degourcy@hetic.net",    "Pierre",       "De gourcy",                          User::STUDENT, 1);
$user->create("ldjamdjian", "ldjamdjian", "leonard.djamdjian@hetic.net",  "Léonard",      "Djamdjian",                          User::STUDENT, 1);
$user->create("ldupuis",    "ldupuis",    "leonard.dupuis@hetic.net",     "Léonard",      "Dupuis",                             User::STUDENT, 1);
$user->create("despinasse", "despinasse", "david.espinasse@hetic.net",    "David",        "Espinasse de sanglier de la bastie", User::STUDENT, 1);
$user->create("aficheux",   "aficheux",   "aude.ficheux@hetic.net",       "Aude",         "Ficheux",                            User::STUDENT, 1);
$user->create("bgoutorbe",  "bgoutorbe",  "boris.goutorbe@hetic.net",     "Boris",        "Goutorbe",                           User::STUDENT, 1);
$user->create("bgresse",    "bgresse",    "bethsabee.gresse@hetic.net",   "Bethsabée",    "Gresse",                             User::STUDENT, 1);
$user->create("phaurie",    "phaurie",    "pierrebrice.haurie@hetic.net", "Pierre-Brice", "Haurie",                             User::STUDENT, 1);
$user->create("thoogstoel", "thoogstoel", "thomas.hoogstoel@hetic.net",   "Thomas",       "Hoogstoël",                          User::STUDENT, 1);
$user->create("pinesta",    "pinesta",    "pierrick.inesta@hetic.net",    "Pierrick",     "Inesta",                             User::STUDENT, 1);
$user->create("llebras",    "llebras",    "leo.lebras@hetic.net",         "Léo",          "Le bras",                            User::STUDENT, 1);
$user->create("glebelt",    "glebelt",    "guillaume.lebelt@hetic.net",   "Guillaume",    "Lebelt",                             User::STUDENT, 1);
$user->create("hlepoutre",  "hlepoutre",  "hadrien.lepoutre@hetic.net",   "Hadrien",      "Lepoutre",                           User::STUDENT, 1);
$user->create("rlimoges",   "rlimoges",   "raphaelle.limoges@hetic.net",  "Raphaëlle",    "Limoges",                            User::STUDENT, 1);
$user->create("alin",       "alin",       "antoine.lin@hetic.net",        "Antoine",      "Lin",                                User::STUDENT, 1);
$user->create("clong",      "clong",      "clement.long@hetic.net",       "Clement",      "Long",                               User::STUDENT, 1);
$user->create("mlussiana",  "mlussiana",  "maxime.lussiana@hetic.net",    "Maxime",       "Lussiana",                           User::STUDENT, 1);
$user->create("cmangwa",    "cmangwa",    "charles.mangwa@hetic.net",     "Charles",      "Mangwa chuisse",                     User::STUDENT, 1);
$user->create("amenegaux",  "amenegaux",  "adrien.menegaux@hetic.net",    "Adrien",       "Menegaux",                           User::STUDENT, 1);
$user->create("rmichay",    "rmichay",    "robin.michay@hetic.net",       "Robin",        "Michay",                             User::STUDENT, 1);
$user->create("jmillet",    "jmillet",    "jennyfer.millet@hetic.net",    "Jennyfer",     "Millet",                             User::STUDENT, 1);
$user->create("gmuller",    "gmuller",    "guillaume.muller@hetic.net",   "Guillaume",    "Muller",                             User::STUDENT, 1);
$user->create("snguyen",    "snguyen",    "sulivan.nguyen@hetic.net",     "Sulivan",      "Nguyen",                             User::STUDENT, 1);
$user->create("apavret",    "apavret",    "arthur.pavret@hetic.net",      "Arthur",       "Pavret de la rochefordiere",         User::STUDENT, 1);
$user->create("apeltre",    "apeltre",    "antoine.peltre@hetic.net",     "Antoine",      "Peltre",                             User::STUDENT, 1);
$user->create("gpillot",    "gpillot",    "gala.pillot@hetic.net",        "Gala",         "Pillot",                             User::STUDENT, 1);
$user->create("arisser",    "arisser",    "anthelme.risser@hetic.net",    "Anthelme",     "Risser",                             User::STUDENT, 1);
$user->create("lrouge",     "lrouge",     "laurence.rouge@hetic.net",     "Laurence",     "Rouge",                              User::STUDENT, 1);
$user->create("csaulnier",  "csaulnier",  "clement.saulnier@hetic.net",   "Clément",      "Saulnier",                           User::STUDENT, 1);
$user->create("sschreiber", "sschreiber", "simon.schreiber@hetic.net",    "Simon",        "Schreiber",                          User::STUDENT, 1);
$user->create("utallepied", "utallepied", "ulysse.tallepied@hetic.net",   "Ulysse",       "Tallepied",                          User::STUDENT, 1);
$user->create("stan",       "stan",       "suongkevin.tan@hetic.net",     "Suong Kévin",  "Tan",                                User::STUDENT, 1);
$user->create("mtellier",   "mtellier",   "margaux.tellier@hetic.net",    "Margaux",      "Tellier",                            User::STUDENT, 1);
$user->create("ptrotsky",   "ptrotsky",   "pierre.trotsky@hetic.net",     "Pierre",       "Trotsky",                            User::STUDENT, 1);
$user->create("gyaici",     "gyaici",     "guillaume.yaici@hetic.net",    "Guillaume",    "Yaici",                              User::STUDENT, 1);
$user->create("azaganelli", "azaganelli", "adrien.zaganelli@hetic.net",   "Adrien",       "Zaganelli",                          User::STUDENT, 1);
$user->create("rzerbib",    "rzerbib",    "raphael.zerbib@hetic.net",     "Raphaël",      "Zerbib",                             User::STUDENT, 1);
$user->create("lzevaco",    "lzevaco",    "lucie.zevaco@hetic.net",       "Lucie",        "Zevaco",                             User::STUDENT, 1);

// G2

$user->create("mallouch",          "mallouch",          "max.allouch@hetic.net",                   "Max",             "Allouch",          User::STUDENT, 2);             
$user->create("balviz",            "balviz",            "blas.alviz@hetic.net",                    "Blas",            "Alviz",            User::STUDENT, 2);               
$user->create("tbacholier",        "tbacholier",        "theo.bacholier@hetic.net",                "Théo",            "Bacholier",        User::STUDENT, 2);           
$user->create("cbasset",           "cbasset",           "camille.basset@hetic.net",                "Camille",         "Basset",           User::STUDENT, 2);              
$user->create("bbergaglia",        "bbergaglia",        "bastien.bergaglia@hetic.net",             "Bastien",         "Bergaglia",        User::STUDENT, 2);             
$user->create("aberneau",          "aberneau",          "alex.berneau@hetic.net",                  "Alex",            "Berneau",          User::STUDENT, 2);             
$user->create("abetoliere",        "abetoliere",        "adrien.betoliere@hetic.net",              "Adrien",          "Betoliere",        User::STUDENT, 2);           
$user->create("tblanco",           "tblanco",           "timothe.blanco@hetic.net",                "Timothé",         "Blanco",           User::STUDENT, 2);              
$user->create("pborensztein",      "pborensztein",      "paul.borensztein@hetic.net",              "Paul",            "Borensztein",      User::STUDENT, 2);         
$user->create("ccastel",           "ccastel",           "cyprien.castel@hetic.net",                "Cyprien",         "Castel",           User::STUDENT, 2);              
$user->create("vchaddouk",         "vchaddouk",         "vanessa.chaddouk@hetic.net",              "Vanessa",         "Chaddouk",         User::STUDENT, 2);            
$user->create("mchanthapanya",     "mchanthapanya",     "mathilde.chanthapanya@hetic.net",         "Mathilde",        "Chanthapanya",     User::STUDENT, 2);        
$user->create("ccharvet",          "ccharvet",          "clement.charvet@hetic.net",               "Clément",         "Charvet",          User::STUDENT, 2);             
$user->create("jclerc",            "jclerc",            "jonathan.clerc@hetic.net",                "Jonathan",        "Clerc",            User::STUDENT, 2);             
$user->create("bcollen",           "bcollen",           "brandon.collen@hetic.net",                "Brandon",         "Collen",           User::STUDENT, 2);              
$user->create("bcorsini",          "bcorsini",          "benjamin.corsini@hetic.net",              "Benjamin",        "Corsini",          User::STUDENT, 2);             
$user->create("sdancermichel",     "sdancermichel",     "sebastien.dancermichel@hetic.net",        "Sébastien",       "Dancer-michel",    User::STUDENT, 2);       
$user->create("ddelorme",          "ddelorme",          "dorian.delorme@hetic.net",                "Dorian",          "Delorme",          User::STUDENT, 2);             
$user->create("gderilleuxbes",     "gderilleuxbes",     "gauthier.derilleuxbes@hetic.net",         "Gauthier",        "Derilleux-bes",    User::STUDENT, 2);       
$user->create("mdine",             "mdine",             "matthis.dine@hetic.net",                  "Matthis",         "Dine",             User::STUDENT, 2);                
$user->create("bdriche",           "bdriche",           "bilal.driche@hetic.net",                  "Bilal",           "Driche",           User::STUDENT, 2);              
$user->create("aduboust",          "aduboust",          "arnaud.duboust@hetic.net",                "Arnaud",          "Duboust",          User::STUDENT, 2);             
$user->create("vfauqueur",         "vfauqueur",         "valerian.fauqueur@hetic.net",             "Valérian",        "Fauqueur",         User::STUDENT, 2);            
$user->create("jferhaoui",         "jferhaoui",         "jasmine.ferhaoui@hetic.net",              "Jasmine",         "Ferhaoui",         User::STUDENT, 2);            
$user->create("rfourreau",         "rfourreau",         "ronan.fourreau@hetic.net",                "Ronan",           "Fourreau",         User::STUDENT, 2);            
$user->create("mgaonach",          "mgaonach",          "maelle.gaonach@hetic.net",                "Maëlle",          "Gaonac'h",         User::STUDENT, 2);            
$user->create("jgirardeau",        "jgirardeau",        "julien.girardeau@hetic.net",              "Julien",          "Girardeau",        User::STUDENT, 2);           
$user->create("vgossioux",         "vgossioux",         "victor.gossioux@hetic.net",               "Victor",          "Gossioux",         User::STUDENT, 2);            
$user->create("ajacoty",           "ajacoty",           "antoine.jacoty@hetic.net",                "Antoine",         "Jacoty",           User::STUDENT, 2);              
$user->create("tkunetz",           "tkunetz",           "theo.kunetz@hetic.net",                   "Théo",            "Kunetz",           User::STUDENT, 2);              
$user->create("mlesellier",        "mlesellier",        "mariealix.lesellier@hetic.net",           "Marie-Alix",      "Lesellier",        User::STUDENT, 2);           
$user->create("jlherm",            "jlherm",            "jeanrene.lherm@hetic.net",                "Jean-René",       "Lherm",            User::STUDENT, 2);               
$user->create("lloriol",           "lloriol",           "leo.loriol@hetic.net",                    "Léo",             "Loriol",           User::STUDENT, 2);              
$user->create("amarrast",          "amarrast",          "aurelien.marrast@hetic.net",              "Aurélien",        "Marrast",          User::STUDENT, 2);             
$user->create("cmarzin",           "cmarzin",           "corentin.marzin@hetic.net",               "Corentin",        "Marzin",           User::STUDENT, 2);              
$user->create("amauriceperoumal",  "amauriceperoumal",  "anne.mauriceperoumal@hetic.net",          "Anne",            "Maurice-peroumal", User::STUDENT, 2);    
$user->create("mmercier",          "mmercier",          "mathieu.mercier@hetic.net",               "Mathieu",         "Mercier",          User::STUDENT, 2);             
$user->create("tmeuneur",          "tmeuneur",          "thadde.meuneur@hetic.net",                "Thaddé",          "Meuneur",          User::STUDENT, 2);             
$user->create("mmorales",          "mmorales",          "maeva.morales@hetic.net",                 "Maeva",           "Morales",          User::STUDENT, 2);             
$user->create("amorand",           "amorand",           "axel.morand@hetic.net",                   "Axel",            "Morand",           User::STUDENT, 2);              
$user->create("lmorgaut",          "lmorgaut",          "louisvictor.morgaut@hetic.net",           "Louis-Victor",    "Morgaut",          User::STUDENT, 2);             
$user->create("enaim",             "enaim",             "emmanuel.naim@hetic.net",                 "Emmanuel",        "Naïm",             User::STUDENT, 2);                
$user->create("rnataf",            "rnataf",            "raphael.nataf@hetic.net",                 "Raphaël",         "Nataf",            User::STUDENT, 2);               
$user->create("lpaulus",           "lpaulus",           "lionel.paulus@hetic.net",                 "Lionel",          "Paulus",           User::STUDENT, 2);              
$user->create("rpiacitelli",       "rpiacitelli",       "raphael.piacitelli@hetic.net",            "Raphaël",         "Piacitelli",       User::STUDENT, 2);          
$user->create("mpozo",             "mpozo",             "melissandre.pozo@hetic.net",              "Mélissandre",     "Pozo",             User::STUDENT, 2);                
$user->create("hquincey",          "hquincey",          "hugo.quincey@hetic.net",                  "Hugo",            "Quincey",          User::STUDENT, 2);             
$user->create("lsadoune",          "lsadoune",          "leo.sadoune@hetic.net",                   "Léo",             "Sadoune",          User::STUDENT, 2);             
$user->create("tsanlis",           "tsanlis",           "thomas.sanlis@hetic.net",                 "Thomas",          "Sanlis",           User::STUDENT, 2);              
$user->create("jschirrmann",       "jschirrmann",       "julie.schirrmann@hetic.net",              "Julie",           "Schirrmann",       User::STUDENT, 2);          
$user->create("dtaing",            "dtaing",            "david.taing@hetic.net",                   "David",           "Taing",            User::STUDENT, 2);               
$user->create("nthomas",           "nthomas",           "nans.thomas@hetic.net",                   "Nans",            "Thomas",           User::STUDENT, 2);              
$user->create("avillani",          "avillani",          "arnaud.villani@hetic.net",                "Arnaud",          "Villani",          User::STUDENT, 2);             
$user->create("cvion",             "cvion",             "clement.vion@hetic.net",                  "Clément",         "Vion",             User::STUDENT, 2);                
$user->create("mzaccardi",         "mzaccardi",         "michael.zaccardi@hetic.net",              "Michaël",         "Zaccardi",         User::STUDENT, 2);            
$user->create("czunda",            "czunda",            "claire.zunda@hetic.net",                  "Claire",          "Zunda",            User::STUDENT, 2);
